### ISSUE TITLE
API and GraphQL requests using login auth token be default

### ISSUE THREAD

**Issue by dreadedhamish** [fikretsengul/flutter_advanced_boilerplate#11]
Troubleshooting why an API request I was making was failing and firing a 401 unauthorised error, when the API allows anonymous requests. Turns out it's reusing the token from the login.

Should authorisation and tokens be abstracted and assignable further down the chain? It would make more sense to me having the option in rest-api-page/networking.

Or is this part of the ideology, in which case I should duplicate modules/dio for each type of request?

**Comment by fikretsengul** [comment]
Thank you for asking about your problems.

First of all, both graphql and dio uses same storage just to demonstrate the logic. I don't think they both will be used in a same project. But if they, you can create another storage to separate them. Secondly, you're getting 401 because we set authorization header as 'Bearer demo_access_token' when we login demo account. So if you don't set the access_token in your header (leaving it as empty) you can successfully get your calls result.

**Comment by dreadedhamish** [comment]
Thanks - yes i figured out how to remove it. It's just a trap for new users who might assume there is no auth header because they haven't set one.
